# Generated by Django 4.0.2 on 2023-03-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=240, null=True)),
                ('department', models.CharField(max_length=240, null=True)),
                ('team', models.CharField(max_length=240, null=True)),
                ('course', models.CharField(max_length=240, null=True)),
                ('fullname', models.CharField(max_length=240, null=True)),
                ('fathername', models.CharField(max_length=240, null=True)),
                ('mothername', models.CharField(max_length=240, null=True)),
                ('dateofbirth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=240, null=True)),
                ('presentaddress1', models.CharField(max_length=240, null=True)),
                ('presentaddress2', models.CharField(max_length=240, null=True)),
                ('presentaddress3', models.CharField(max_length=240, null=True)),
                ('pincode', models.CharField(max_length=240, null=True)),
                ('district', models.CharField(max_length=240, null=True)),
                ('state', models.CharField(max_length=240, null=True)),
                ('country', models.CharField(max_length=240, null=True)),
                ('permanentaddress1', models.CharField(max_length=240, null=True)),
                ('permanentaddress2', models.CharField(max_length=240, null=True)),
                ('permanentaddress3', models.CharField(max_length=240, null=True)),
                ('permanentpincode', models.CharField(max_length=240, null=True)),
                ('permanentdistrict', models.CharField(max_length=240, null=True)),
                ('permanentstate', models.CharField(max_length=240, null=True)),
                ('permanentcountry', models.CharField(max_length=240, null=True)),
                ('mobile', models.CharField(max_length=240, null=True)),
                ('alternativeno', models.CharField(max_length=240, null=True)),
                ('employee_id', models.CharField(default='', max_length=240, null=True)),
                ('email', models.EmailField(max_length=240, null=True)),
                ('password', models.CharField(max_length=240, null=True)),
                ('idproof', models.FileField(blank=True, null=True, upload_to='images/')),
                ('photo', models.FileField(blank=True, null=True, upload_to='images/')),
                ('attitude', models.IntegerField(default='0')),
                ('creativity', models.IntegerField(default='0')),
                ('workperformance', models.IntegerField(default='0')),
                ('joiningdate', models.DateField(auto_now_add=True, null=True)),
                ('startdate', models.DateField(auto_now_add=True, null=True)),
                ('enddate', models.DateField(auto_now_add=True, null=True)),
                ('status', models.CharField(default='active', max_length=240, null=True)),
                ('tl_id', models.IntegerField(blank=True, default='0', null=True)),
                ('projectmanager_id', models.IntegerField(blank=True, default='0', null=True)),
                ('total_pay', models.IntegerField(default='0')),
                ('payment_balance', models.IntegerField(default='0')),
                ('account_no', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('ifsc', models.CharField(default='', max_length=200, null=True)),
                ('bank_name', models.CharField(blank=True, default='', max_length=240, null=True)),
                ('bank_branch', models.CharField(default='', max_length=240, null=True)),
                ('payment_status', models.CharField(default='', max_length=200, null=True)),
                ('offerqr', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('relieveqr', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('expqr', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('hrmanager', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('confirm_salary', models.CharField(default='', max_length=10)),
                ('confirm_salary_status', models.CharField(default='0', max_length=255)),
                ('payment_file_downlod', models.FileField(blank=True, null=True, upload_to='images/')),
                ('total_amount', models.IntegerField(default='0')),
                ('payment_amount_date', models.DateField(blank=True, null=True)),
                ('salary_pending', models.CharField(default='', max_length=100)),
                ('salary_status', models.CharField(default='', max_length=10)),
                ('trainer_level', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('hr_designation', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('reg_status', models.CharField(default='0', max_length=10)),
                ('trainee_delay', models.IntegerField(default=0)),
            ],
        ),
    ]
