# Generated by Django 4.0.2 on 2023-03-14 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0002_qualification_extracurricular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_registration',
            name='course',
        ),
        migrations.RemoveField(
            model_name='user_registration',
            name='team',
        ),
    ]
