# Generated by Django 4.0.2 on 2023-03-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0004_client_information_internship_work_progress_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='cl_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
