# Generated by Django 4.0.2 on 2023-03-15 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0005_clint_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='addi_client_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labels', models.CharField(blank=True, default='', max_length=220, null=True)),
                ('discription', models.TextField(blank=True, default='', null=True)),
                ('file', models.ImageField(blank=True, null=True, upload_to='images/requirement/')),
            ],
        ),
        migrations.CreateModel(
            name='client_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('client_address', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('client_mail', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('bs_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('bs_website', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('bs_location', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('client_files', models.ImageField(blank=True, null=True, upload_to='images/client/')),
                ('seo', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('seo_txt', models.TextField(blank=True, default='', null=True)),
                ('seo_file', models.ImageField(blank=True, null=True, upload_to='images/requirement/')),
                ('smm', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('smm_txt', models.TextField(blank=True, default='', null=True)),
                ('smm_file', models.ImageField(blank=True, null=True, upload_to='images/requirement/')),
                ('sem', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('sem_txt', models.TextField(blank=True, default='', null=True)),
                ('sem_file', models.ImageField(blank=True, null=True, upload_to='images/requirement/')),
                ('em', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('em_txt', models.TextField(blank=True, default='', null=True)),
                ('em_file', models.ImageField(blank=True, null=True, upload_to='images/requirement/')),
                ('cm', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('cm_txt', models.TextField(blank=True, default='', null=True)),
                ('cm_file', models.ImageField(blank=True, null=True, upload_to='images/requirement/')),
                ('am', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('am_txt', models.TextField(blank=True, default='', null=True)),
                ('am_file', models.ImageField(blank=True, null=True, upload_to='images/requirement/')),
                ('mm', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('mm_txt', models.TextField(blank=True, default='', null=True)),
                ('mm_file', models.ImageField(blank=True, null=True, upload_to='images/requirement/')),
                ('vm', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('vm_txt', models.TextField(blank=True, default='', null=True)),
                ('vm_file', models.ImageField(blank=True, null=True, upload_to='images/requirement/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DMcoreapp.user_registration')),
            ],
        ),
        migrations.DeleteModel(
            name='clint_information',
        ),
        migrations.AddField(
            model_name='addi_client_info',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DMcoreapp.client_information'),
        ),
        migrations.AddField(
            model_name='addi_client_info',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DMcoreapp.user_registration'),
        ),
    ]
