# Generated by Django 4.0.2 on 2023-03-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0005_work_cl_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_work',
            name='task',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
