# Generated by Django 4.0.2 on 2023-03-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0006_addi_client_info_client_information_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addi_client_info',
            name='section',
            field=models.CharField(blank=True, default='', max_length=220, null=True),
        ),
    ]
