# Generated by Django 4.0.2 on 2023-03-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0006_daily_work_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress_report',
            old_name='Work',
            new_name='work',
        ),
        migrations.AddField(
            model_name='progress_report',
            name='task',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
