# Generated by Django 4.0.2 on 2023-03-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMcoreapp', '0008_alter_addi_client_info_discription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addi_client_info',
            name='discription',
            field=models.TextField(blank=True, default='Null', null=True),
        ),
        migrations.AlterField(
            model_name='addi_client_info',
            name='labels',
            field=models.CharField(blank=True, default='Null', max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='addi_client_info',
            name='section',
            field=models.CharField(blank=True, default='Null', max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='client_information',
            name='am',
            field=models.CharField(blank=True, default='Null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client_information',
            name='am_txt',
            field=models.TextField(blank=True, default='Null', null=True),
        ),
        migrations.AlterField(
            model_name='client_information',
            name='bs_location',
            field=models.CharField(blank=True, default='Null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client_information',
            name='bs_name',
            field=models.CharField(blank=True, default='Null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client_information',
            name='bs_website',
            field=models.CharField(blank=True, default='Null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client_information',
            name='client_address',
            field=models.CharField(blank=True, default='Null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client_information',
            name='client_mail',
            field=models.CharField(blank=True, default='Null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client_information',
            name='client_name',
            field=models.CharField(blank=True, default='Null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client_information',
            name='cm',
            field=models.CharField(blank=True, default='Null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client_information',
            name='cm_txt',
            field=models.TextField(blank=True, default='Null', null=True),
        ),
        migrations.AlterField(
            model_name='client_information',
            name='em',
            field=models.CharField(blank=True, default='Null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client_information',
            name='em_txt',
            field=models.TextField(blank=True, default='Null', null=True),
        ),
        migrations.AlterField(
            model_name='client_information',
            name='mm',
            field=models.CharField(blank=True, default='Null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client_information',
            name='mm_txt',
            field=models.TextField(blank=True, default='Null', null=True),
        ),
        migrations.AlterField(
            model_name='client_information',
            name='sem',
            field=models.CharField(blank=True, default='Null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client_information',
            name='sem_txt',
            field=models.TextField(blank=True, default='Null', null=True),
        ),
        migrations.AlterField(
            model_name='client_information',
            name='seo',
            field=models.CharField(blank=True, default='Null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client_information',
            name='seo_txt',
            field=models.TextField(blank=True, default='Null', null=True),
        ),
        migrations.AlterField(
            model_name='client_information',
            name='smm',
            field=models.CharField(blank=True, default='Null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client_information',
            name='smm_txt',
            field=models.TextField(blank=True, default='Null', null=True),
        ),
        migrations.AlterField(
            model_name='client_information',
            name='vm',
            field=models.CharField(blank=True, default='Null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client_information',
            name='vm_txt',
            field=models.TextField(blank=True, default='Null', null=True),
        ),
    ]
